const products=[
 {id:'bouteilles-bubble-gum',name:'Bouteilles bubble gum',brand:'Assia Sweet',price:3.90,category:'Acidulés',flavor:'Bubble gum',tag:'Le goût de l’enfance',image:'vrac-bouteille-bubble-gum-acide-halal.jpg',texture:true,description:'Le duo rose et bleu qui ne passe jamais inaperçu. Un goût bubble gum et une touche acidulée pour retrouver les petits plaisirs de l’enfance.'},
 {id:'fraises-sauvages',name:'Fraises sauvages',brand:'Assia Sweet',price:3.50,category:'Gélifiés',flavor:'Fraise',tag:'Fruité',image:'vrac-fraise-sauvage-sucre-halal.jpg',description:'De petites fraises tendres et sucrées, à glisser dans un sachet à partager. Toute la gourmandise d’un grand classique, dans un petit format.'},
 {id:'rubans-arc-en-ciel',name:'Rubans arc-en-ciel',brand:'Damel',price:3.90,category:'Acidulés',flavor:'Multifruits',tag:'Ça pétille',image:'damel-ceinture-arc-en-ciel-acidulee-halal.jpg',texture:true,description:'Toutes les couleurs, un seul plaisir. Des rubans fruités à dérouler, avec juste ce qu’il faut d’acidulé pour réveiller les papilles.'},
 {id:'oursons-fruites',name:'Oursons fruités',brand:'Assia Sweet',price:3.50,category:'Gélifiés',flavor:'Multifruits',tag:'Les intemporels',image:'vrac-ours-assortis-sucree-halal.jpg',description:'Les petits oursons qui mettent tout le monde d’accord. Un assortiment fruité et moelleux pour les pauses gourmandes et les moments à partager.'},
 {id:'anneaux-peche',name:'Anneaux à la pêche',brand:'Assia Sweet',price:3.90,category:'Acidulés',flavor:'Pêche',tag:'Tout en douceur',image:'vrac-anneaux-peche-halal.jpg',texture:true,description:'Une forme ronde, une texture tendre et un délicieux goût de pêche. Des anneaux enrobés de sucre pour une parenthèse fruitée.'},
 {id:'bananes-sucrees',name:'Bananes sucrées',brand:'Assia Sweet',price:3.50,category:'Gélifiés',flavor:'Banane',tag:'Le classique',image:'vrac-banane-jaune-sucre-halal.jpg',description:'Le petit bonbon jaune au goût inimitable. Une douceur à la banane pour composer votre sélection de classiques.'},
 {id:'coeurs-fraise',name:'Cœurs rouge & blanc',brand:'Assia Sweet',price:3.90,category:'Acidulés',flavor:'Fraise',tag:'À partager',image:'vrac-coeur-rouge-blanc-acide-halal.jpg',texture:true,description:'Un petit cœur, beaucoup de gourmandise. Des bonbons rouge et blanc à offrir, à partager, ou simplement à garder pour soi.'},
 {id:'anneaux-pomme',name:'Anneaux à la pomme',brand:'Assia Sweet',price:3.90,category:'Acidulés',flavor:'Pomme',tag:'Touche acidulée',image:'vrac-anneaux-pomme-acide-halal.jpg',texture:true,description:'Une note de pomme et un enrobage acidulé. Des anneaux fruités qui donnent un peu de peps à votre sélection.'}
];
products.push(...[{"id": "cerises", "name": "Cerises lisses", "brand": "Dulceplus", "category": "Gélifiés", "flavor": "Cerise", "image": "cerises.jpg", "price": 3.5, "tag": "À découvrir", "description": "Cerises lisses : une nouvelle envie à ajouter à votre sélection gourmande. Choisissez votre format et composez votre panier.", "texture": false}, {"id": "crocodiles", "name": "Crocodiles fruités", "brand": "Dulceplus", "category": "Gélifiés", "flavor": "Multifruits", "image": "crocodiles.jpg", "price": 3.5, "tag": "À découvrir", "description": "Crocodiles fruités : une nouvelle envie à ajouter à votre sélection gourmande. Choisissez votre format et composez votre panier.", "texture": false}, {"id": "cola", "name": "Bouteilles cola", "brand": "Dulceplus", "category": "Acidulés", "flavor": "Cola", "image": "cola.jpg", "price": 3.9, "tag": "À découvrir", "description": "Bouteilles cola : une nouvelle envie à ajouter à votre sélection gourmande. Choisissez votre format et composez votre panier.", "texture": true}, {"id": "pasteque", "name": "Tranches de pastèque", "brand": "Dulceplus", "category": "Acidulés", "flavor": "Pastèque", "image": "pasteque.jpg", "price": 3.9, "tag": "À découvrir", "description": "Tranches de pastèque : une nouvelle envie à ajouter à votre sélection gourmande. Choisissez votre format et composez votre panier.", "texture": true}, {"id": "marshmallow", "name": "Fleurs marshmallow", "brand": "Finitronc", "category": "Guimauves", "flavor": "Vanille", "image": "marshmallow.jpg", "price": 3.5, "tag": "À découvrir", "description": "Fleurs marshmallow : une nouvelle envie à ajouter à votre sélection gourmande. Choisissez votre format et composez votre panier.", "texture": false}, {"id": "mures", "name": "Mûres gourmandes", "brand": "Damel", "category": "Gélifiés", "flavor": "Mûre", "image": "mures.webp", "price": 3.5, "tag": "À découvrir", "description": "Mûres gourmandes : une nouvelle envie à ajouter à votre sélection gourmande. Choisissez votre format et composez votre panier.", "texture": false}, {"id": "vers", "name": "Vers acidulés", "brand": "Dulceplus", "category": "Acidulés", "flavor": "Multifruits", "image": "vers.jpg", "price": 3.9, "tag": "À découvrir", "description": "Vers acidulés : une nouvelle envie à ajouter à votre sélection gourmande. Choisissez votre format et composez votre panier.", "texture": true}, {"id": "briques-pasteque", "name": "Briques pastèque", "brand": "Dulceplus", "category": "Acidulés", "flavor": "Pastèque", "image": "briques-pasteque.jpg", "price": 3.9, "tag": "À découvrir", "description": "Briques pastèque : une nouvelle envie à ajouter à votre sélection gourmande. Choisissez votre format et composez votre panier.", "texture": true}]);

const orderData=[{id:'AS-1028',customer:'Camille M.',date:'7 sept. 2026',total:32.70,status:'À préparer'},{id:'AS-1027',customer:'Thomas R.',date:'7 sept. 2026',total:45.50,status:'À préparer'},{id:'AS-1026',customer:'Sarah B.',date:'7 sept. 2026',total:24.90,status:'Expédiée'},{id:'AS-1025',customer:'Julie L.',date:'6 sept. 2026',total:58.60,status:'Livrée'},{id:'AS-1024',customer:'Mehdi A.',date:'6 sept. 2026',total:19.40,status:'Expédiée'}];
console.log(JSON.stringify({products,orders:orderData}));